# Generated by Django 2.1 on 2018-11-12 05:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=255, verbose_name='상품명')),
                ('price', models.PositiveIntegerField(default=0, verbose_name='가격')),
            ],
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(blank=True, default='', max_length=55, verbose_name='옵션 색상')),
                ('size', models.CharField(blank=True, default='', max_length=55, verbose_name='옵션 색상')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='옵션 재고 수량')),
                ('goods', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='options', to='goods.Goods', verbose_name='어떤 Goods 의 Option 인지')),
            ],
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=255, verbose_name='공급자명')),
            ],
        ),
        migrations.CreateModel(
            name='Shipping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('FREE', '무료 배송'), ('PREPAY', '유료 배송')], default='FREE', max_length=10, verbose_name='배송비 부과 여부')),
                ('price', models.PositiveIntegerField(default=0, verbose_name='가격')),
                ('can_bundle', models.BooleanField(default=True, verbose_name='묶음 배송 가능 여부')),
            ],
        ),
        migrations.AddField(
            model_name='goods',
            name='provider',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='goods', to='goods.Provider', verbose_name='제공자'),
        ),
        migrations.AddField(
            model_name='goods',
            name='shipping',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='goods', to='goods.Shipping', verbose_name='배송정책'),
        ),
    ]
