# Generated by Django 2.1 on 2018-11-12 06:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='shipping',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='goods', to='goods.Shipping', verbose_name='배송정책'),
        ),
    ]
