# Generated by Django 2.1 on 2018-11-12 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_auto_20181112_0637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='color',
            field=models.CharField(blank=True, choices=[('yellow', '노랑'), ('blue', '파랑'), ('red', '빨강'), ('green', '초록'), ('yellowgreen', '연초록'), ('violet', '자주'), ('black', '검정')], default='yellow', max_length=55, verbose_name='옵션 색상'),
        ),
        migrations.AlterField(
            model_name='option',
            name='size',
            field=models.CharField(blank=True, choices=[('S', 'small'), ('M', 'medium'), ('L', 'large')], default='S', max_length=55, verbose_name='옵션 색상'),
        ),
    ]
